### ISSUE TITLE
Plugin not Valid on Omeka 2.3

### ISSUE THREAD

**Issue by fabioce** [Daniel-KM/XmlImport#1]
I have unzipped XmlImport into plugins folder, but my Omeka 2.3 installation said me that the plugin isn't valid.

Have you idea why?
Thanks

**Comment by Daniel-KM** [comment]
Hi,

I use the plugin with a 2.3 install too and it works fine. The directory should be renamed XmlImport and rights of the folder should be set as usual.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by fabioce** [comment]
I have CsvImport ver. 2.0.3 per Roy Rosenzweig Center for History and New Media
The permission are ok.

**Comment by Daniel-KM** [comment]
Hi,

I just try a fresh install of Omeka 2.3 and of my plugin, and it works fine. Don't forget to rename the folder of the plugin to XmlImport. I just updated the plugin too to work with the last release of the official Csv Import.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by fabioce** [comment]
yes you are right.
I solved, changed name from XmlImport-master in XmlImport
also for CsvImport
