### ISSUE TITLE
XmlImport Configuration

### ISSUE THREAD

**Issue by fabioce** [Daniel-KM/XmlImport#2]
Hi,
I don't understand where I need to write this configuration:

saxonb-xslt -ext:on -versionmsg:off -s:%1$s -xsl:%2$s -o:%3$s
CLASSPATH=/usr/share/java/Saxon-HE.jar java net.sf.saxon.Transform -ext:on -versionmsg:off -s:%1$s -xsl:%2$s -o:%3$s

If I try to write this into plugin configuration area, the result is an empty input text.

**Comment by Daniel-KM** [comment]
Hi,

The readme is not clear, but in fact, the first command is the one to use in old release of Debian, the second in the current one.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by fabioce** [comment]
Ok I understand that I need to use this:
CLASSPATH=/usr/share/java/Saxon-HE.jar java net.sf.saxon.Transform -ext:on -versionmsg:off -s:%1$s -xsl:%2$s -o:%3$s
But where?
I must write this into xmlimport configuration?

**Comment by Daniel-KM** [comment]
Hi,

In the second field of the config page of the plugin : http://www.example.com/admin/plugins/config?name=XmlImport

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by fabioce** [comment]
I tryed,
but nothing the result is an empty input text.

**Comment by Daniel-KM** [comment]
Hi,

The package libsaxonhe-java should be installed (this is for xslt v2).
You can try the command on the command line too.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by fabioce** [comment]
Ok, I installed the package libsaxonhe-java, and I tryed to insert:
CLASSPATH=/usr/share/java/Saxon-HE-9.4.0.7.jar java net.sf.saxon.Transform -ext:on -versionmsg:off -s:%1$s -xsl:%2$s -o:%3$s
but the inpute text result empty.
I can only insert
/usr/share/java/Saxon-HE-9.4.0.7.jar

**Comment by fabioce** [comment]
I need to correct me.
I'm able to insert only this:
/usr/share/java/Saxon-HE-9.4.0.7.jar java net.sf.saxon.Transform

**Comment by Daniel-KM** [comment]
Hi,

I try the last plugin with a fresh installation of Omeka and all works fine with the command I provide. I don't understand the issue. 

You should be able to launch such a command in the terminal:

```
cd /path/to/Omeka/plugins/XmlImport
CLASSPATH=/usr/share/java/Saxon-HE.jar java net.sf.saxon.Transform -ext:on -versionmsg:off -s:'xml_files/test_generic_item_automap.xml' -xsl:'libraries/generic_item.xsl' -o:'/tmp/test.csv'
```

Adapt it to your installation and use it.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

The readme has been clarified.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
