### ISSUE TITLE
Import Xml file record with more than 1 file

### ISSUE THREAD

**Issue by fabioce** [Daniel-KM/XmlImport#3]
Hi,
I tryed to import the example xml file:
test_generic_item.xml
But I don't see the record "Walden". In the result there is 1 skipped record.
The "Walden" record is the nly one record with more than 1 file image.
Why?

**Comment by Daniel-KM** [comment]
Hi,

This file has three items and five files from Wikipedia. If you don't see them, it means the xml processor is not configured.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by fabioce** [comment]
I'm able to insert with an xml file with this tags:
`<file>
<file>first-path</file>
</file>
<file1>
<file1>second-path</file1>
</file1>`

**Comment by Daniel-KM** [comment]
Hi,

The converter is not strict. As long as there are data that can be converted into csv, it convert it.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by ghost** [comment]
Hi Daniel,
I have the same problem written by @fabioce. I use Omeka 2.3 with the latest version of XmlImport.
In plugin configuration tab I correctly entered the path of the xsl file (<code>~ /XmlImport/libraries</code>) and the path to the XSLT processor (<code>/usr/bin/saxonb-xslt</code>).
I also launched from a terminal the command
 <code>cd ~ /Omeka/plugins/XmlImport CLASSPATH = /usr/share/java/Saxon-HE.jar java net.sf.saxon.Transform -ext:on -versionmsg:off -s:'xml_files/test_generic_item_automap.xml' -xsl:'libraries/generic_item.xsl' -o:'/tmp/test.csv'.</code> 
It ended successfully.

You say it might be a problem with xml processor that is Not configured. Can you help me? How can i configure the xml processor? 
I use Ubuntu 14.04 Server with Apache2

Thank you

**Comment by Daniel-KM** [comment]
Hi,

`/usr/bin/saxonb-xslt` is used for the old version of Debian, you should set the following command in the config page: 

```
CLASSPATH=/usr/share/java/Saxon-HE.jar java net.sf.saxon.Transform -ext:on -versionmsg:off -s:%1$s -xsl:%2$s -o:%3$s
```

I updated the readme to clarify it.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
